---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
- hosts: nginx
  become: yes
  become_user: root
  become_method: sudo
  vars:
    gitlab_edition: "gitlab-ee"
  roles:
    - { role: geerlingguy.gitlab }
  tasks:
